// 自动生成 by core/quickchat.js —— 请勿手改;游戏更新后重跑 node core/quickchat.js 并重编 VPK
// 桥离线时的快捷语音模板兜底语料(双语,来自本地真实文件)。
// 指纹以全局变量暴露,客户端 syncQuickChat 握手用;旧兑底文件无此变量 → 客户端按指纹缺失路径处理
LCT_QUICKCHAT_FALLBACK_FINGERPRINT = "fnv1a-77d762f5";
LCT_QUICKCHAT_FALLBACK_TEMPLATES = [
 "攻击分路",
 "Attacking Lane",
 "攻击 1 级",
 "Attacking T1",
 "攻击 2 级",
 "Attacking T2",
 "防守基地",
 "Defending Base",
 "防守分路",
 "Defending Lane",
 "防守 1 级",
 "Defending T1",
 "None",
 "推进滑索",
 "Pushing Zipline",
 "我可以治疗你，{s:param_1}",
 "I can heal you {s:param_1}",
 "帮忙护送灵瓮",
 "Help with Urn",
 "帮我护送灵瓮",
 "Help me deliver the urn",
 "攻击{s:hero_name}",
 "Attack {s:hero_name}",
 "马上回来",
 "Be Right Back",
 "小心",
 "Careful",
 "防守分路",
 "Defend Lane",
 "撤退",
 "Get Back",
 "上啊",
 "Go",
 "上了",
 "Going In",
 "比赛很精彩",
 "Good Game",
 "干得漂亮",
 "Good Job",
 "干得漂亮",
 "Good Job",
 "往基地走了",
 "Headed To Base",
 "{s:hero_name}往蓝路走了",
 "{s:hero_name} Headed Blue",
 "{s:hero_name}往绿路走了",
 "{s:hero_name} Headed Green",
 "{s:hero_name}往绿路走了",
 "{s:hero_name} Headed Green",
 "{s:hero_name}往黄路走了",
 "{s:hero_name} Headed Yellow",
 "帮助",
 "Help",
 "等等/等一下",
 "Wait/Hold Up",
 "我回来了",
 "I'm Back",
 "No",
 "来了",
 "On my Way",
 "Taunt {s:hero_name}",
 "Praise {s:hero_name}",
 "推进分路",
 "Push Lane",
 "复生石掉落了",
 "Rejuv's Dropping",
 "一起行动",
 "Stay Together",
 "眩晕",
 "Stun",
 "Stun {s:hero_name}",
 "打得很漂亮",
 "Well Played",
 "好的",
 "Yes",
 "取消",
 "Cancel",
 "我来清理步兵",
 "I'll Clear Troopers",
 "有危险",
 "It's Dangerous",
 "我来包抄",
 "I'll Flank",
 "跟着我",
 "Follow Me",
 "往这边来了",
 "Headed This Way",
 "离开区域",
 "Leaving Area",
 "到这去",
 "Let's Go Here",
 "我们在这躲躲",
 "Let's Hide Here",
 "在这碰头吧",
 "Meet Here",
 "敌人消失",
 "Missing",
 "蓝路敌人消失",
 "Missing Blue",
 "绿路敌人消失",
 "Missing Green",
 "敌人消失",
 "Missing",
 "绿路敌人消失",
 "Missing Green",
 "黄路敌人消失",
 "Missing Yellow",
 "掩护我",
 "Cover Me",
 "算了吧",
 "Nevermind",
 "没准备好团战",
 "Not Ready For Teamfight",
 "乘胜追击",
 "Press The Advantage",
 "Respond 'On My Way'",
 "撤退",
 "Retreat",
 "这有敌人",
 "Enemy Here",
 "谢了",
 "Thanks",
 "谢了",
 "Thanks",
 "我马上回来",
 "Be right back",
 "小心",
 "Care",
 "防守分路",
 "Defend Lane",
 "防守蓝路",
 "Defend Blue",
 "防守绿路",
 "Defend Green",
 "防守绿路",
 "Defend Green",
 "防守黄路",
 "Defend Yellow",
 "撤退",
 "Get Back",
 "上啊",
 "Go",
 "我要上了",
 "I'm going in",
 "比赛很精彩",
 "Good Game",
 "干得漂亮",
 "Good Job",
 "干得漂亮",
 "Good Job",
 "往基地走了",
 "Headed To Base",
 "往蓝路走了",
 "Headed to Blue",
 "往绿路走了",
 "Headed to Green",
 "往绿路走了",
 "Headed to Green",
 "往黄路走了",
 "Headed to Yellow",
 "需要帮助",
 "Need Help",
 "蓝路需要帮助",
 "Need Help on Blue",
 "绿路上需要帮助",
 "Need Help on Green",
 "紫路需要帮助",
 "Need Help on Purple",
 "黄路需要帮助",
 "Need Help on Yellow",
 "等待{s:param_1}",
 "Wait {s:param_1}",
 "我回来了",
 "I'm Back",
 "敌人消失",
 "Missing",
 "No",
 "来了",
 "On my way",
 "Taunt {s:hero_name}",
 "Praise {s:hero_name}",
 "推进",
 "Push",
 "复生石掉落了",
 "Rejuv's Dropping",
 "跟我来",
 "Come with Me",
 "一起行动",
 "Stay Together",
 "眩晕",
 "Stun",
 "打得很漂亮",
 "Well Played",
 "没问题",
 "Affirmative",
 "我来对付步兵",
 "I'll deal with the troopers",
 "这里很危险",
 "It's dangerous here",
 "我来包抄他们",
 "I'll flank 'em",
 "准备抓人",
 "Going to Gank",
 "往分路走了",
 "Headed To Lane",
 "我要离开这个区域了",
 "I'm leaving the area",
 "我们在这躲躲",
 "Let's hide here",
 "我们在这碰头吧",
 "Let's meet here",
 "蓝路敌人消失",
 "Missing Blue",
 "绿路敌人消失",
 "Missing Green",
 "{s:param_1}不见了",
 "{s:param_1} is Missing",
 "绿路敌人消失",
 "Missing Green",
 "黄路敌人消失",
 "Missing Yellow",
 "掩护我",
 "Cover me",
 "算了吧",
 "Nevermind",
 "我还没准备好团战",
 "I'm not ready for a teamfight",
 "我们要乘胜追击",
 "We need to press the advantage",
 "谢了",
 "Thanks",
 "谢了",
 "Thanks",
 "推进蓝路",
 "Push Blue",
 "推进绿路",
 "Push Green",
 "推进紫路",
 "Push Purple",
 "推进黄路",
 "Push Yellow",
 "回复给：",
 "Responding to:",
 "{s:param_1}还要冷却{s:param_2}秒",
 "{s:param_1} is on cooldown for {s:param_2}s",
 "{s:param_1}准备就绪",
 "{s:param_1} is ready",
 "没问题",
 "Affirmative",
 "一起去干掉{s:param_1}",
 "Let's take out {s:param_1}",
 "去打他们的守护神",
 "Let's take their Patron",
 "蓝路需要帮助",
 "Blue Needs Help",
 "小心{s:param_1}",
 "Careful {s:param_1}",
 "防守",
 "Defend",
 "防守基地",
 "Defend the Base",
 "防守蓝路",
 "Defend Blue",
 "防守绿路",
 "Defend Green",
 "防守绿路",
 "Defend Green",
 "防守黄路",
 "Defend Yellow",
 "小心！{s:param_1}有{s:param_2}",
 "Careful! {s:param_1} has {s:param_2}",
 "他们在打中区头目",
 "They're taking mid",
 "我要上了",
 "I'm going in",
 "干得漂亮",
 "Good job",
 "绿路需要帮助",
 "Green Needs Help",
 "往蓝路走了",
 "Headed to Blue",
 "往绿路走了",
 "Headed to Green",
 "往绿路走了",
 "Headed to Green",
 "往黄路走了",
 "Headed to Yellow",
 "我回来了",
 "I'm Back",
 "灵瓮在此",
 "Spirit Urn is here",
 "不稳定裂隙在这里",
 "Unstable Rift is here",
 "我们去蓝路吧",
 "Let's go Blue",
 "我们去绿路吧",
 "Let's go Green",
 "我们去绿路吧",
 "Let's go Green",
 "我们去黄路吧",
 "Let's go Yellow",
 "蓝路敌人消失",
 "Missing Blue",
 "绿路敌人消失",
 "Missing Green",
 "绿路敌人消失",
 "Missing Green",
 "黄路敌人消失",
 "Missing Yellow",
 "蓝路需要帮助",
 "Need help Blue",
 "绿路上需要帮助",
 "Need help Green",
 "绿路上需要帮助",
 "Need help Green",
 "黄路需要帮助",
 "Need help Yellow",
 "算了",
 "Cancel That",
 "干得不错",
 "Nice work",
 "我马上就到",
 "On my Way",
 "绿路需要帮助",
 "Green Needs Help",
 "我们去推进蓝路吧",
 "Let's Push Blue",
 "我们去推绿路吧",
 "Let's Push Green",
 "我们去推绿路吧",
 "Let's Push Green",
 "我们去推进黄路吧",
 "Let's Push Yellow",
 "跟着我",
 "Follow me",
 "Pull back",
 "我看到 {s:param_1}",
 "I see {s:param_1}",
 "我看到{s:param_2}点生命的{s:param_1}",
 "I see {s:param_1} with {s:param_2} health",
 "一起行动",
 "Stay Together",
 "快晕住{s:param_1}",
 "Stun {s:param_1}",
 "去打他们的核心",
 "Let's take out their core",
 "我们去拿下中区头目",
 "Let's take mid",
 "谢谢",
 "Thank You",
 "敌人",
 "the enemy",
 "他们",
 "They're",
 "他们在打我们的守护神",
 "They're taking our Patron",
 "{s:param_1}准备就绪",
 "{s:param_1} is ready",
 "黄路需要帮助",
 "Yellow Needs Help"
];
