// 自动生成 by core/quickchat.js —— 请勿手改;游戏更新后重跑 node core/quickchat.js 并重编 VPK
// 模板参数约束用的专名表(英/中;多词英文名保留空格;含英雄/物品/能力名)。
LCT_GAMENAMES_FALLBACK = [
 "+100% card bonus",
 "+Fire Rate",
 "+Move Speed",
 "+Weapon Damage",
 "+{s:AbilityCharges} Charge",
 "+{s:AbilityCharges} Charges",
 "+{s:AbilityCharges}充能",
 "+{s:AbilityUnitTargetLimit} targets",
 "+{s:BleedDPSPerStack}生命流失每秒伤害并提升元灵增强系数",
 "+{s:CombatBarrier}屏障并提升屏障元灵增强系数",
 "+{s:DPS} DPS",
 "+{s:DPS}每秒伤害<br>+{s:ShockRadius}米半径",
 "+{s:DamageMultiplier}x damage multiplier",
 "+{s:Damage} Damage and +1 Charge",
 "+{s:Damage} 伤害<br>+1 充能",
 "+{s:Damage}伤害<br>提升元灵增强系数",
 "+{s:Damage}伤害并提升元灵增强系数",
 "+{s:DroneCount} additional drones",
 "+{s:ImmobilizeDuration}s Duration",
 "+{s:ImmobilizeDuration}秒持续时间",
 "+{s:MaxHealthMelee}近战额外生命值并提升元灵增强系数",
 "+{s:Radius}伤害<br>施加-{s:FireRateSlow}%射速",
 "+{s:RegenPercent}% health recovery",
 "- 子弹抗性",
 "-Bullet Resist",
 "100% Chance of Lightning",
 "360 Cone",
 "Abilities Disabled",
 "Ability is always active",
 "Abort",
 "Abrams",
 "Absorbing Damage",
 "Acrobat",
 "Active Reload",
 "Add Attach Time",
 "Add Drones",
 "Aerial Supremacy",
 "Afflicted",
 "After ambushing:",
 "Afterburn",
 "Afterburn Damage Amp",
 "Air Drop",
 "Akimbo",
 "Alchemical Fire",
 "Alchemical Flask",
 "All Stakes are Blessed",
 "Ambush Damage",
 "Ammo Scavenger",
 "Ancient Shield",
 "Apex Combat",
 "Apocalypse",
 "Apollo",
 "Apply a damaging barrier",
 "Apply a delayed area stun",
 "Apply an escalating slow",
 "Apply stacking bleed to the target",
 "Arc Cannon",
 "Arcane Surge",
 "Architect",
 "Arctic Beam",
 "Arctic Beam Slow",
 "Arctic Blast",
 "Armor Boost",
 "Armor Break",
 "Armor Piercing Rounds",
 "Asleep",
 "Assassin",
 "Assassinate",
 "Astral Walk",
 "Attack",
 "Audience Participation",
 "Aura of Pain",
 "Aura of Suffering",
 "Ava",
 "Baited",
 "Ballista",
 "Ballistic Enchantment",
 "Bandolier",
 "Banished",
 "Barrage - Damage Amp",
 "Barrage Slow",
 "Barrier",
 "Bashdown",
 "Battle Vest",
 "Bebop",
 "Become invincible and more powerful",
 "Being Vindicta Pushed",
 "Being dragged",
 "Belt Feed",
 "Berserker",
 "Billy",
 "Binding Word",
 "Bio Blast",
 "Blasted",
 "Bleed",
 "Bleeding",
 "Blessed Tac-Vest",
 "Blinding Light",
 "Blink in and out of existence",
 "Blood Exchange",
 "Blood Tribute",
 "Bloodletting",
 "Bloodscent",
 "Boho",
 "Bomb on you",
 "Bombard an area with rockets",
 "Bomber",
 "Bonus Damage",
 "Bonus Weapon Damage",
 "Bookwyrm",
 "Boost your fire rate",
 "Boosting",
 "Boot Kick",
 "Borrow Life",
 "Borrowed Decree",
 "Bottled Phantasmicide",
 "Boundless Spirit",
 "Bruising Shot",
 "Building Power",
 "Bullet Armor",
 "Bullet Armor Reduced",
 "Bullet Damage Amp Wall",
 "Bullet Dance",
 "Bullet Flurry",
 "Bullet Lifesteal",
 "Bullet Resilience",
 "Bullet Resist Shredder",
 "Bullet Storm",
 "Burn Effect:",
 "Burned by Riptide",
 "Burning from Afterburn",
 "Burning from Incendiary",
 "Burrow",
 "Burst Fire",
 "Cadence",
 "Cadence Anthem",
 "Calico",
 "Call Bell",
 "Camouflaged",
 "Can be Recast within {s:RecastTime}s",
 "Can't hide",
 "Cancel",
 "Cancel Fissure Wall",
 "Cancel Flame Dash",
 "Cancel Life Drain",
 "Capacitor",
 "Captivating Read",
 "Captive Audience",
 "Capture Hyperline",
 "Capturing Hyperline",
 "Card Trick",
 "Cards",
 "Carpet Bombing",
 "Catalyst Damage Amp",
 "Catapult",
 "Celeste",
 "Celestial Blessing",
 "Chain Damage",
 "Chain Gang",
 "Chain Lightning",
 "Chain Pulling In",
 "Chain Radius",
 "Chained",
 "Chained to Billy",
 "Charge into combat",
 "Charge up a long range shot",
 "Charged Bomb",
 "Charged Shot",
 "Charged Tackle",
 "Charging",
 "Charmed",
 "Cheat Death",
 "Choking Incense",
 "Chomping an Enemy",
 "Clawdril",
 "Clear placement",
 "Cloak of Opportunity",
 "Close Doors",
 "Close Quarters",
 "Club",
 "Cold Front",
 "Cold Metal",
 "Colossus",
 "Combat Barrier",
 "Combat Drone Active",
 "Combo",
 "Compress Cooldown",
 "Concussive Combustion",
 "Conjure Dragon",
 "Conjure Missiles",
 "Conjure a wall to block your foes",
 "Consecrating Grenade",
 "Consecrating Grenade - Pure",
 "Consume",
 "Consume an enemy trooper or neutral",
 "Containment",
 "Contaminate",
 "Converge",
 "Counterspell",
 "Cowboy",
 "Crawling Plague",
 "Create a dangerous web",
 "Create an impenetrable healing dome",
 "Create electric arcs with your shots",
 "Crimson Slash",
 "Crippling Headshot",
 "Crit Vulnerable",
 "Crow Familiar",
 "Crushing Fists",
 "Crushing Leap",
 "Cultist Sacrifice",
 "Cursed",
 "Cursed Relic",
 "DPS",
 "Damage Boost",
 "Damage Reduced",
 "Damage Stacks",
 "Damage Vulnerability",
 "Damage Vulnerbility",
 "Damage and debuff enemies nearby",
 "Damage and slow enemies",
 "Damage and slow enemies in the area",
 "Damage random targets around you",
 "Dash forward and slash enemies",
 "Dazed",
 "Dazzling Trick",
 "Death Immune",
 "Death Slam",
 "Death Tax",
 "Death Tax Power",
 "Debuff Reducer",
 "Decay",
 "Decoy",
 "Decoy Active",
 "Decreased Courage",
 "Defend",
 "Defensive Fortress",
 "Defer a portion of damage taken",
 "Delayed Stun",
 "Demolitions Expert",
 "Demontrigger Blitz",
 "Deploy Combat Drone",
 "Deploy a healing spirit",
 "Deploy a statue that survey's an area",
 "Diamond",
 "Disable",
 "Disable armor after teleport",
 "Disarm enemies in front of you",
 "Disarmed",
 "Disarming Hex",
 "Disarming...",
 "Disengaging Sigil",
 "Dispel Magic",
 "Divine Barrier",
 "Diviner's Kevlar",
 "Djinn's Mark",
 "Dodging",
 "Doorman",
 "Doorway",
 "Double Dagger",
 "Double Edge",
 "Dragging someone",
 "Drain health from nearby enemies",
 "Draw",
 "Draw two cards",
 "Drifter",
 "Drone",
 "Drone Camera",
 "Drone Crash",
 "Drone DPS",
 "Drone Infrared Camera",
 "Drone Teleport",
 "Drone also gets player items",
 "Drones",
 "Drop Soul Urn",
 "Druid",
 "Duo",
 "Duration Extender",
 "Dust Devil",
 "Dust Devil - Slow",
 "Dust Storm",
 "Dynamo",
 "EXPIRING",
 "Earthquake",
 "Echo",
 "Echo Boost",
 "Echo Shard",
 "Echo spreads to nearby enemies",
 "Electric Slippers",
 "Empower yourself and a nearby ally",
 "Empowered Melee",
 "Empowered Round",
 "Enable Drone infrared Camera",
 "Encased in Glass",
 "Enchanter's Emblem",
 "End Aura",
 "End Channel",
 "End the Curse",
 "Endless Magazine",
 "Enduring Speed",
 "Enduring Spirit",
 "Enemy Spirit Stolen",
 "Energy Link",
 "Energy Spirits",
 "Energy Strike",
 "Energy Surge",
 "Energy Warp",
 "English",
 "Enrage Bonuses",
 "Enraged",
 "Entangling Bola",
 "Entangling Thorns",
 "Entering Stealth",
 "Escalating Exposure",
 "Escalating Resilience",
 "Escape Artist",
 "Escape the Hotel",
 "Essence Bomb",
 "Essence Theft",
 "Eternal Gift",
 "Eternal Night",
 "Ethereal Shift",
 "Exploding Uppercut",
 "Explosion",
 "Explosive Headshots",
 "Express Shot",
 "Extended Magazine",
 "Extra Charge",
 "Extra Health",
 "Extra Regen",
 "Extra Spirit",
 "Extra Stamina",
 "Fade out of sight",
 "Fading",
 "Faraday Cage",
 "Fathom",
 "Fear",
 "Fervor Stack",
 "Fight",
 "Figment Barrier",
 "Fire Crossbow",
 "Fire Rate Increased",
 "Fire Scarabs",
 "Fixated",
 "Fixation",
 "Flak Cannon",
 "Flakshot",
 "Flame Dash",
 "Flame Dashing",
 "Flame Imp",
 "Flawless Advance",
 "Fleetfoot",
 "Flight",
 "Flog",
 "Fly towards an enemy target",
 "Fly your owl to damage enemies from afar",
 "Flying Cloak",
 "Flying Nimbus",
 "Flying Slash",
 "Flying Slash Slow",
 "Focus Lens",
 "Follow",
 "Following Hero:",
 "Following Trooper:",
 "Force of Nature",
 "Fortitude",
 "Fortuna",
 "Freezing",
 "Frenzy",
 "Frost Grenade",
 "Frostbite Charm",
 "Frozen",
 "Frozen Shelter",
 "Fry all enemies in a large area",
 "Full Auto",
 "Fury Trance",
 "Fusion Bomb",
 "Fusion Scalpel",
 "Gadget Man",
 "Gadgeteer",
 "Gain a Barrier and move speed",
 "Galvanic Storm",
 "Generic Person",
 "Getting Chomped",
 "Glass Cannon",
 "Glass Cannon v2",
 "Glider",
 "Glitched",
 "Gloom Bombs",
 "Go For The Throat",
 "Golden Goose Egg",
 "Grab an enemy and drag them behind you",
 "Graf",
 "Grand Finale",
 "Grapple",
 "Grapple Arm",
 "Grapple Hook",
 "Grapple Hook Wall Hanging",
 "Grasping Hands",
 "Gravedigging",
 "Graves",
 "Greater Expansion",
 "Grenade",
 "Grey Talon",
 "Grit",
 "Ground Strike",
 "Guardian Ward",
 "Guided Owl",
 "Gun Damage",
 "Gun Damage - Crit",
 "Gunner",
 "Gunslinger",
 "Gutshot",
 "Hack Enemy Units",
 "Harnessing Power",
 "Hat Trick",
 "Hat Trick Disarms",
 "Haunting Scream",
 "Haunting Shot",
 "Haunting Spectres",
 "Haunting Spirits",
 "Haze",
 "Head Shot Bonus Cooldown",
 "Head Stomp",
 "Headhunter",
 "Headshot Booster",
 "Heal yourself and those around you",
 "Healbane",
 "Healing",
 "Healing Booster",
 "Healing Disabled",
 "Healing Nova",
 "Healing Rite",
 "Healing Tempo",
 "Heals for {s:HealPercent}% damage taken",
 "Heals from targets ahead of you",
 "Health Stolen",
 "Health Swap",
 "Heart",
 "Heavy Barrage",
 "Heavy Barrage Slow",
 "Heavy Drone",
 "Heavy Rage",
 "Hellfire Salvo",
 "Helper Following",
 "Hero kills refill all charges",
 "Heroic Aura",
 "Hex-Lined Snap Trap",
 "Hex-Sealed Knuckles",
 "Hexafoil Ward",
 "Hidden In Smoke",
 "High Explosive",
 "High-Velocity Rounds",
 "Hijack",
 "Holliday",
 "Hollow Point",
 "Home Base",
 "Hook Blade",
 "Hop To Ally",
 "Hotel Guest",
 "Human Form:",
 "Hungry",
 "Hungry:",
 "Hunter's Aura",
 "Hyper Beam",
 "Ice Grenade Slow",
 "Ice Path",
 "Igniting",
 "Immobilize nearby enemies",
 "Immobilized",
 "Immobilizing...",
 "Immunity",
 "Improved Spirit",
 "In Shop",
 "In Smoke",
 "Increase the agility of your Slide",
 "Increased Attack Speed",
 "Increased Move Speed",
 "Indomitable",
 "Infecting",
 "Infection",
 "Infernal Resilience",
 "Infernus",
 "Infinite Rounds",
 "Infuse Weapon",
 "Infuser",
 "Inhibitor",
 "Initializing...",
 "Inject your enemies with a deadly venom",
 "Inner Fire",
 "Intensifying Magazine",
 "Intertwine",
 "Invisible",
 "Ion Dagger",
 "Ionizing",
 "Ira Domini",
 "Itani Lo Sahn",
 "Ivy",
 "Jar of Dead",
 "Jeté",
 "Juggernaut",
 "Jumpstart",
 "Kali",
 "Kelvin",
 "Killing Blow",
 "Kinetic Carbine",
 "Kinetic Dash",
 "Kinetic Pulse",
 "Knockdown",
 "Kudzu Connection",
 "Lady Geist",
 "Large increase to Heavy's ammo",
 "Lash",
 "Lasso Chained",
 "Last Breath",
 "Last Stand",
 "Launch a boomerang that flies back",
 "Launch a damaging ball of lightning",
 "Launch a guided bolt of magic",
 "Leap at your enemies",
 "Leaping Slash",
 "Leave area to escape binding",
 "Leech",
 "Leeching...",
 "Lethal Venom",
 "Life Drain",
 "Lifestrike",
 "Lifethread",
 "Lifting - Silenced + Disarmed",
 "Light Eater",
 "Lightning Ball",
 "Lightning Ball Slow",
 "Lightning Roll",
 "Lightning Scroll",
 "Lightning Strike",
 "Lil Helpers",
 "Lil Helpers'",
 "Lock on to Target",
 "Long Range",
 "Love Bites",
 "Love Bites (On-Hit)",
 "Lucky Card",
 "Lucky Shot",
 "Luggage Cart",
 "Luminous Strike Burn",
 "Lycan Curse",
 "Mad Bomber",
 "Magic Carpet",
 "Magnetic Flux",
 "Majestic Leap",
 "Majestic Leap - Disabled",
 "Make a target bleed over time",
 "Malice",
 "Malice Amplification",
 "Marked for Lifesteal",
 "Marksman",
 "Mauling Leap",
 "McGinnis",
 "Mecha Guy",
 "Medic Drone",
 "Medic Drone - deploying",
 "Medicating",
 "Medicinal Specter",
 "Melee",
 "Melee Charge",
 "Melee Lifesteal",
 "Melee also EMP's enemies",
 "Mercurial Magnum",
 "Metal Skin",
 "Mina",
 "Mine Field",
 "Mini Turret - Slow",
 "Mirage",
 "Misdirection",
 "Misdirection zone",
 "Mo & Krill",
 "Monster Rounds",
 "Mortar Sentry",
 "Movement Slow",
 "Mud Shield",
 "Muted",
 "Mystic Burst",
 "Mystic Conduit",
 "Mystic Expansion",
 "Mystic Regeneration",
 "Mystic Reverb",
 "Mystic Shot",
 "Mystic Slow",
 "Mystic Vulnerability",
 "Mystical Piano",
 "Nap Heal",
 "Napalm",
 "Napalm Effects:",
 "Napping",
 "Naptime",
 "Nekomata Ward",
 "Nox Nostra",
 "Nullification Burst",
 "Obscured",
 "Occilioblade",
 "Omnicharge Signet",
 "On Activate",
 "On Barrier Expire:",
 "On Barrier:",
 "On Blasted Melee:",
 "On Buff:",
 "On Bullet Hit",
 "On Cast:",
 "On Death:",
 "On Debuff:",
 "On Debuff: Silences Stamina Usage",
 "On Double Hit:",
 "On Empowered Cast:",
 "On Enemy Hit:",
 "On Explode",
 "On Friendly Hit:",
 "On Headshot:",
 "On Hero Collide:",
 "On Hero Hit:",
 "On Hero Kill:",
 "On Hit",
 "On Hit:",
 "On Impact",
 "On Impact:",
 "On Isolated Hero Death:",
 "On Kill:",
 "On Landing:",
 "On Max Stacks Proc",
 "On Max Stacks:",
 "On Melee:",
 "On Perfect Hold:",
 "On Player Hit",
 "On Pommel Hit:",
 "On Portal",
 "On Proc:",
 "On Revive:",
 "On Slide:",
 "On Stack:",
 "On The Hunt",
 "On Wall Hit",
 "On Wall Hit:",
 "On hit",
 "Open Wounds",
 "Opening Rounds",
 "Opera",
 "Order",
 "Overload",
 "Pack Hunter",
 "Paige",
 "Pain Battery",
 "Paradox",
 "Paradoxical Swap",
 "Passive:",
 "Patron's Healing",
 "Peeking In Smoke",
 "Per Hero Hit",
 "Pest Barrier",
 "Petrified",
 "Petrify",
 "Petrifying Bola",
 "Phalanx",
 "Phantom Strike",
 "Phoenix",
 "Picking up ammo pack...",
 "Pillow Toss",
 "Pissed",
 "Plant a bomb on an enemy",
 "Planting bomb...",
 "Plated Armor",
 "Play",
 "Player Camera",
 "Plot Armor",
 "Pocket",
 "Point Blank",
 "Pool of Light",
 "Potency",
 "Potent Vapors",
 "Pounce",
 "Powder Burn",
 "Powder Keg",
 "Power Jump",
 "Power Slash",
 "Power Surge",
 "Precision Shots that escalate damage",
 "Prism Blast",
 "Project Mind",
 "Propulsion Gel",
 "Protective Shell",
 "Proximity explosion",
 "Psychic Pulse",
 "Pull in a target to you",
 "Pull in and stun the enemy team",
 "Pulled",
 "Pulse Grenade",
 "Pulse Grenade - Spirit Resist Down",
 "Pulse Grenade Damage Amp",
 "Punch someone away from you",
 "Puppeted",
 "Puppeteer",
 "Put an enemy to sleep",
 "Quantum Entanglement",
 "Quarantined",
 "Queen of Shadows",
 "Quick Cooldowns",
 "Quicksilver Reload",
 "Rabbit Hex",
 "Radiant Daggers",
 "Radiant Regeneration",
 "Rage",
 "Rage Stacks",
 "Rain of Arrows",
 "Rake",
 "Rallying Charge",
 "Ram Damage Boost",
 "Ram Fortitude",
 "Rapid Fire",
 "Rapid Recharge",
 "Rapid Rounds",
 "Raven",
 "Reactive Armor",
 "Reactive Barrier",
 "Ready to Escape",
 "Rebirth",
 "Rebirth Bonus Health",
 "Rebuttal",
 "Recall Ava",
 "Recast",
 "Recharging Rush",
 "Reduce total cooldown by 1s per unit hit",
 "Reduced Cooldown",
 "Reflect",
 "Reflect Basic Damage",
 "Reflect Shield",
 "Refresher",
 "Regeneration",
 "Rejuvenating Aurora",
 "Release a wave of spectral spiders",
 "Rem",
 "Remain Covered",
 "Remote Bomb",
 "Rescue Beam",
 "Restorative Locket",
 "Restorative Shot",
 "Retaliate",
 "Return Fire",
 "Return back to your human form.",
 "Return from Ava",
 "Return to Shadows",
 "Returning...",
 "Reveal enemies through walls",
 "Revealed",
 "Revelation",
 "Revelation Curse",
 "Revenant",
 "Ricochet",
 "Ricochet Dagger",
 "Riposte",
 "Rising Ram",
 "Rocket Drone",
 "Rocket Drone - deploying",
 "Royal Flush",
 "Runed Gauntlets",
 "Rusted Barrel",
 "Rutger",
 "SILENCER",
 "Sand Blast",
 "Sand Blasted",
 "Sanguine Retreat",
 "Sapper",
 "Satiated",
 "Satiated:",
 "Scorn",
 "Scourge",
 "Screwjab",
 "Screwjab Dagger",
 "Seek Shelter",
 "Seismic Impact",
 "Sekhmet's Spirit",
 "Send out a Spirit Cat to grab enemies",
 "Send out a tornado that slows enemies",
 "Sentry",
 "Sentry Bullet Resist Debuff",
 "Sentry Rocket",
 "Seraphim Wings",
 "Serrated Knife",
 "Serrated Knive",
 "Serrated Knives",
 "Serrated Knives Bleed Damage",
 "Seven",
 "Shadow Box",
 "Shadow Form",
 "Shadow Step",
 "Shadow Strike",
 "Shadow Transformation",
 "Shadow Weave",
 "Sharpshooter",
 "Shattered",
 "Shield Guy",
 "Shield Toss",
 "Shining Wonder",
 "Shiv",
 "Shock Wave",
 "Shocking Reanimation",
 "Shoot a blast of bio mass",
 "Shoot enemies to set them on fire",
 "Shoryuken",
 "Shoulder Charge",
 "Shrink Ray",
 "Sigil Amp",
 "Silence Contraptions",
 "Silence Wave",
 "Silenced",
 "Silencer",
 "Silktrap",
 "Silver",
 "Sinclair",
 "Singing Anthem",
 "Singing a Lullaby",
 "Singularity",
 "Siphon",
 "Siphon Bullets",
 "Siphon Energy",
 "Siphon Life",
 "Skipshot",
 "Sky Monk",
 "Skyrunner",
 "Slam Ball",
 "Slam Fire",
 "Slammed",
 "Sleep Dagger",
 "Sleeping",
 "Sleeve Toss",
 "Sleeve Toss Immobilizes",
 "Sleeve toss",
 "Sleight of Hand",
 "Slice and Dice",
 "Slice and Dice Heal Debuff",
 "Slingshot",
 "Slither",
 "Slork Poison Sprayer",
 "Slork Scalding Spray",
 "Slow",
 "Slow Firerate & Movement",
 "Slow and Damage nearby enemies",
 "Slowed",
 "Slowing Bullets",
 "Slowing Hex",
 "Smelt",
 "Smoke Bomb",
 "Smoke and Mirrors",
 "Snakeform",
 "Snipe injured targets for massive damage",
 "Soul Exchange",
 "Soul Explosion",
 "Soul Rebirth",
 "Spade",
 "Spectral Assistant",
 "Spectral Silk",
 "Spectral Wall",
 "Speed Boost",
 "Speed Drone",
 "Speed Drone - deploying",
 "Speed around on a floating path of ice",
 "Spellbreaker",
 "Spellslinger",
 "Spew napalm that amplifies your damage",
 "Spidertide",
 "Spin",
 "Spirit Armor",
 "Spirit Armor Reduced",
 "Spirit Burn",
 "Spirit Draining",
 "Spirit Echo",
 "Spirit Immune",
 "Spirit Lasso",
 "Spirit Lifesteal",
 "Spirit Rend",
 "Spirit Resilience",
 "Spirit Resist Down",
 "Spirit Sap",
 "Spirit Shield",
 "Spirit Shielding",
 "Spirit Shredder Bullets",
 "Spirit Snare",
 "Spirit Snare Debuff",
 "Spirit Snatch",
 "Spirit Stolen",
 "Spirit Strike",
 "Spirit and Bullet Armor",
 "Spiritual Overflow",
 "Split Shot",
 "Spreading Flames",
 "Sprint Boots",
 "Stabilizer",
 "Stack damage amplification on an enemy",
 "Stake",
 "Stalker",
 "Stamina Mastery",
 "Static Charge",
 "Steal health from an enemy over time",
 "Stealth",
 "Stealthed",
 "Sticky Bomb",
 "Stolen Glance",
 "Stomp Debuff",
 "Stone Form",
 "Stop Charging",
 "Storm Cloud",
 "Storm Cloud Lightning Strike",
 "Street Cleaner",
 "Strength",
 "Strength from Shadows",
 "Stumble",
 "Stunned",
 "Summon",
 "Summon your faithful assistant",
 "Summons your drone.",
 "Superior Cooldown",
 "Superior Duration",
 "Suppressor",
 "Surge of Power",
 "Swan",
 "Swap positions with an enemy hero.",
 "Swift Striker",
 "Swish",
 "Switches Camera from Drone to Player",
 "Switches Camera from Player to Drone",
 "Tackling",
 "Tag Along",
 "Tag Along Recast",
 "Tail Whack",
 "Take control of Ava",
 "Take flight and empower your weapon",
 "Taking a snooze...",
 "Tankbuster",
 "Target Practice",
 "TargetDummy",
 "Teargas",
 "Teargas Grenade",
 "Telekinesis",
 "Teleport to the targeted location",
 "Tempest",
 "Tempo",
 "Temporary Reanimation",
 "Tempted...",
 "Tesla Bullets",
 "Tesla Coil",
 "Tesla Coil Nearby",
 "Test Hero",
 "Tether",
 "Tether your enemies to the ground",
 "Tethered",
 "Tethered to the ground",
 "The Boss",
 "The Curse Beckons...",
 "The Doorman",
 "The Hunger",
 "The enemy can see your position",
 "Throw Explosive",
 "Throw a ball of scrap that stuns enemies",
 "Throw a barrel that explodes when shot",
 "Throw a blade that returns to you",
 "Throw a poison jar",
 "Throw a slowing dagger",
 "Throw a sticky bomb on an enemy",
 "Throw homing cards",
 "Throw out cluster bombs",
 "Thumper",
 "Time Bomb",
 "Time Wall",
 "Timeless Emblem",
 "Titanic Magazine",
 "Tokamak",
 "Torment Pulse",
 "Toss a petrifying bola",
 "Toughness",
 "Toxic Bullets",
 "Toxic Mess",
 "Transcendent Cooldown",
 "Transform your enemy into a rabbit",
 "Trapper",
 "Trapper's Delight",
 "Trigger Fissure Wall",
 "Trophy Collector",
 "Turn both allies and enemies into stone",
 "UBER INVULNERABILITY",
 "Uber Charge",
 "Uber Charging",
 "Umbrella Maneuver",
 "Unburrow",
 "Unleash a blast of energy at your target",
 "Unleash a flurry of bullets around you",
 "Unleash a massive damaging beam",
 "Unstable Concoction",
 "Unsticking",
 "Unstoppable",
 "Uppercut Move Speed",
 "Uproar",
 "Upswing",
 "Utility Drone",
 "Vampire",
 "Vampiric Burst",
 "Vandal",
 "Vanished",
 "Vanishing Act",
 "Veil Fire Rate",
 "Veil Walker",
 "Veil Walker Invisibility",
 "Venator",
 "Vexing Bolt",
 "Victor",
 "Vindicta",
 "Vindicta Leap",
 "Vindicta Nest",
 "Vindicta's Mark",
 "Viscous",
 "Visible to Enemy",
 "Void Sphere +Fire Rate",
 "Vortex Web",
 "Vyper",
 "Waiting for match start",
 "Wall Damage Debuff",
 "Warden",
 "Warp Stone",
 "Weakening",
 "Weakening Headshot",
 "Weapon Boost",
 "Weapon Drain Pulse",
 "Weapon Frozen",
 "Weapon Infused",
 "Weapon Jammed",
 "Weapon Jammer",
 "Weapon Shielding",
 "Weapon has been Jammed",
 "Weathermaker",
 "Weave Fate",
 "Webbed",
 "Weighted Shots",
 "Well Rested",
 "Werewolf Form:",
 "When Active:",
 "When Inactive:",
 "While Blasted:",
 "While Blessed:",
 "While Rage is Full",
 "While Transformed:",
 "Whirling Blade",
 "Willpower",
 "Wing Blast",
 "Witching Hour",
 "Witchmail",
 "Wither & Die",
 "Wraith",
 "Wrecked",
 "Wrecked:",
 "Wrecker",
 "Wrecking Ball",
 "Yamato",
 "You and nearby allies move much faster",
 "You have a Gigantic Sword",
 "Zealot",
 "Zealot Courage Drain",
 "english",
 "{s:AbilityCooldown}s Cooldown",
 "{s:AbilityCooldown}秒冷却时间",
 "{s:AbilityCooldown}秒冷却时间<br>提升速度增强系数",
 "{s:AbilityDuration}s Charge Duration<br>",
 "{s:AbilityDuration}秒冲刺持续时间<br>",
 "{s:RecastTime}秒内可再次施放",
 "{s:}% Max Health Damage",
 "一网打尽",
 "一网打尽治疗减益",
 "上界福佑",
 "不屈之志",
 "不治魔咒",
 "不稳定化合物",
 "与一名敌方英雄互换位置",
 "与一名敌方英雄互换当前生命值",
 "与英雄相撞时：",
 "中止",
 "临终之息",
 "主基地",
 "主的愤怒",
 "主角护体",
 "举起敌人并将其猛砸到地上",
 "乘胜追击",
 "书龙",
 "乱影迷踪",
 "乱心雷矢",
 "亚伯兰",
 "人形态：",
 "人造巨灵",
 "代行敕令",
 "任意门",
 "伏击后：",
 "伏灵陷阱",
 "伏灵陷阱减益效果",
 "休息充足",
 "传送石",
 "传送至目标位置",
 "伤上加伤",
 "伤害减少",
 "余威久久",
 "余威回荡",
 "作祟尖叫",
 "作祟幽影",
 "作祟鬼影",
 "佩吉",
 "使目标持续流失生命",
 "倒下时：",
 "借命",
 "假人靶子",
 "健步疾射",
 "催化剂伤害提升",
 "催泪手雷",
 "催泪瓦斯",
 "元灵免疫",
 "元灵压制",
 "元灵吸取",
 "元灵吸收",
 "元灵套索",
 "元灵常驻",
 "元灵抗性降低",
 "元灵护体",
 "元灵护甲",
 "元灵护甲降低",
 "元灵护盾",
 "元灵撕裂",
 "元灵收割",
 "元灵漫溢",
 "元灵燃烧",
 "元灵衰竭",
 "元灵防护",
 "先发强袭",
 "全自动",
 "公羊伤害提升",
 "六叶结界",
 "六角陷阱",
 "关门",
 "冰冻庇护",
 "冰天雪地",
 "冰封路径",
 "冰霜手雷",
 "冰霜手雷减速",
 "冲锋陷阵",
 "冷却压缩",
 "冻结",
 "准备逃跑",
 "凌空越步",
 "减益缩短",
 "减速",
 "减速弹",
 "减速魔咒",
 "凝固汽油弹",
 "凝固汽油弹效果：",
 "击中友军时：",
 "击中敌人时：",
 "击中时",
 "击中玩家时",
 "击倒英雄时：刷新技能和持续时间",
 "击败时：",
 "击败英雄时：",
 "刚毅",
 "创建一面能够极大减慢投射物速度的墙",
 "刷新环",
 "剑客无情",
 "剑柄击中时：",
 "加强施法时：",
 "加速回复",
 "动力卡宾枪",
 "动能冲刺",
 "动能脉冲",
 "劳什",
 "势不可挡",
 "升空飞跃",
 "升空飞跃已禁用",
 "卡厉可",
 "卡牌戏法",
 "危险蛇毒",
 "即将失效",
 "原地复活",
 "双刃飞袭",
 "双重命中时：",
 "发呆",
 "发射一个具有伤害性的球状闪电",
 "发射一股生物质爆炸波",
 "发射十字弓",
 "取消固定",
 "受到套索束缚",
 "受到福佑时：",
 "受到魅惑",
 "变得无敌且更为强大",
 "变身时：",
 "叠加时：",
 "口袋",
 "召唤你忠实的助手",
 "召唤出一堵墙来阻挡敌人",
 "召唤导弹",
 "召回艾娃",
 "向下猛击",
 "向四周爆发一阵弹雨",
 "向敌人投掷粘性炸弹",
 "吞噬光芒",
 "否决爆发",
 "启用时：",
 "吸取敌人元灵",
 "吸取附近敌人的生命值",
 "呼叫铃",
 "命中时",
 "命中时：",
 "命中时：<br>淘汰生命低于{s:ExecuteThreshold}%的敌人",
 "命中英雄时：",
 "咒印铁拳",
 "咒缚在呼唤……",
 "哈雷黛",
 "唤龙术",
 "嗜血",
 "嗜血：",
 "回应射击",
 "回春极光",
 "回音碎片",
 "在漂浮的冰封路径上快速移动",
 "在目标身上放置炸弹",
 "在落单敌方英雄附近时+{s:BonusMoveSpeed}米/秒移动速度",
 "坚毅之心",
 "坚韧",
 "塞赫麦特之灵",
 "墙体伤害减益",
 "增加滑行时的灵活度",
 "复活时：",
 "复燃",
 "复燃伤害提升",
 "夜晚霸主",
 "大伤元气",
 "大和",
 "天谴圣物",
 "天赐之礼",
 "天锤压顶",
 "天鹅舞伶",
 "头弹奖励",
 "头弹弱防",
 "头弹时：",
 "头弹破防",
 "奇点",
 "奇能",
 "妙手奇技",
 "子弹之舞",
 "子弹击中时",
 "子弹回复",
 "子弹坚甲",
 "子弹护甲",
 "孤猎",
 "守护神的治疗",
 "完美击中英雄时：<br>治疗{s:HealFixedHealth}",
 "完美施放时：",
 "容光焕发",
 "寒霜护符",
 "对作用区域中的敌人造成伤害并减速",
 "对敌人叠加伤害增强",
 "对敌人施加叠加流失生命效果",
 "对敌人造成伤害并减速",
 "对敌方英雄施加延迟触发的范围型眩晕",
 "对目标造成的子弹伤害持续增加",
 "对等还击",
 "对附近的敌人造成伤害和负面效果",
 "寻猎季节",
 "射击会创造出电弧",
 "射速增长量",
 "将别人从身边打飞",
 "将敌人变为兔子",
 "将敌人束缚于地面",
 "小小帮手",
 "小憩",
 "小憩治疗",
 "小睡片刻",
 "尖锋短刀",
 "尖锋短刀流失生命伤害",
 "尘卷风",
 "尘卷风 - 减速",
 "尘土护盾",
 "层层防御",
 "屏障",
 "屏障结束时：",
 "屹立不倒",
 "岚梦",
 "巅峰之战",
 "巨人",
 "巨型弹匣",
 "巫师护甲",
 "已石化",
 "希弗",
 "帮手跟随中",
 "幸免于难",
 "幸运一击",
 "幸运卡牌",
 "幻影屏障",
 "幻影突袭",
 "幽冥女王",
 "幽影瞬步",
 "幽灵助手",
 "应急屏障",
 "延迟眩晕",
 "开尔文",
 "弹幕 - 伤害增强",
 "弹幕减速",
 "弹无虚发",
 "弹跳飞弹",
 "弹道附魔",
 "强化子弹",
 "强化自己和附近的一名友军",
 "强化重击",
 "强效扩张",
 "形成一个无法穿透的治疗罩",
 "御空行者",
 "心灵投射",
 "快手连发",
 "快速启动",
 "念力",
 "怒意之潮",
 "怒气值",
 "怒气值满时",
 "怒气冲天",
 "怨念",
 "怨念提升",
 "恢复",
 "恢复部分受到的伤害",
 "悖论",
 "悖论置换",
 "惊恐万状",
 "惊雷之示",
 "惊雷之示干扰",
 "意志力",
 "成为诱饵",
 "战斗屏障",
 "战斗背心",
 "所有木桩都受过福佑",
 "打个盹儿……",
 "扔出一个毒罐子",
 "扔出具有石化作用的飞索",
 "扩容弹匣",
 "扰动",
 "技能始终为生效状态",
 "把目标拉到身边",
 "抑制术",
 "抓住一个敌人并将其拖到身后",
 "抓钩臂",
 "投掷一个被击中即会爆炸的火药桶",
 "投掷出具有减速效果的匕首",
 "投掷集束弹",
 "投掷魔法卡牌",
 "护卫结界",
 "拉扯锁链",
 "拉近敌方队伍并使其眩晕",
 "拾弹能手",
 "持续吸取敌人的生命值",
 "持续施法期间光环提供+{s:MovementSpeedBonus}米移动速度",
 "按住敌方英雄迅猛出击",
 "挥伞",
 "掘墓",
 "控制艾娃",
 "掷出一把会飞回来的利刃",
 "提升自身射速",
 "撕咬跃击",
 "撞上丝网",
 "撞击时",
 "撞击时：",
 "撞到墙壁时：",
 "撞墙时：",
 "撼天动地",
 "攻击前方目标获得治疗",
 "放置一个限制敌人移动的陷阱",
 "故人之罐",
 "敌之灾患",
 "方块",
 "施加一道会造成伤害的屏障",
 "施加不断提高的减速效果",
 "施加减益时：<br>沉默耐力使用",
 "施加延迟触发的范围型眩晕",
 "施放一波幽灵蜘蛛",
 "施放时：",
 "施放破坏力巨大的光束",
 "施术之手",
 "旋击",
 "旋转",
 "无双魔术师",
 "无名氏",
 "无尽弹匣",
 "无瑕突进",
 "无限弹匣",
 "时间之墙",
 "明光打击灼烧",
 "明辉匕首",
 "显示",
 "暂时复苏",
 "暗影变身术",
 "暗影突袭",
 "暗魂形态",
 "暴动之羊",
 "最高叠加层数触发时",
 "未启用时：",
 "机遇斗篷",
 "束缚之爪",
 "束缚之言",
 "束缚于地面",
 "来去无踪",
 "来自复燃的炙烤",
 "极地冰暴",
 "极寒光束",
 "极寒光束减速效果",
 "枕头大战",
 "枯萎凋零",
 "柒",
 "标记为生命吸取",
 "格瑞墓",
 "梅花",
 "棱镜冲击",
 "模仿大师",
 "欲念",
 "正在施药",
 "正在流失生命",
 "正在点燃",
 "正在等待比赛开始",
 "武器伤害",
 "武器伤害 - 强击",
 "武器冻结",
 "武器加强",
 "武器防护",
 "死亡猛击",
 "殷红贡礼",
 "每秒伤害",
 "毒弹",
 "毒性区域",
 "比利",
 "比波普",
 "水银重弹",
 "永恒之夜",
 "永恒纹章",
 "沃督",
 "沉睡",
 "沉睡中",
 "沉睡匕首",
 "沉默之潮",
 "沉默子弹",
 "沙暴",
 "治疗之环",
 "治疗仪式",
 "治疗强化",
 "治疗律动",
 "治疗自己和周围的友军",
 "法术反制",
 "波米",
 "流失生命",
 "测试英雄",
 "海魇",
 "消耗部分生命来发射可以造成伤害的炸弹",
 "淡出视线",
 "清除放置",
 "渡鸦",
 "渡鸦仆使",
 "滑行时：",
 "满足",
 "满足：",
 "潜行",
 "澎湃电力",
 "激活时",
 "火力凶猛",
 "火力渐升",
 "火药桶",
 "火药燃烧",
 "火速充能",
 "灰爪",
 "灰飞烟灭",
 "灵体漫步",
 "灵力扩增",
 "灵力无边",
 "灵力灌注",
 "灵力高涨",
 "灵异子弹",
 "灵异爬虫",
 "灵能涌动",
 "灵蛇化身",
 "灵雾舒愈",
 "灵魂互换",
 "灵魂爆炸",
 "灵魅",
 "炫目戏法",
 "炸弹附身",
 "炼金之火",
 "炼金瓶",
 "炽天使之翼",
 "炽焱",
 "烂醉",
 "烂醉时：",
 "烂醉的近战攻击时：",
 "烈焰冲刺",
 "烈焰圣甲虫",
 "烈焰小魔",
 "烟雾弹",
 "燃烧效果：",
 "爆炸",
 "爆炸勾拳",
 "爆炸时",
 "爱的轻啮",
 "爱的轻啮（击中时）",
 "特异供奉",
 "特斯拉弹",
 "狂乱",
 "狂战士",
 "狙击",
 "狩猎中途",
 "狱火飞降",
 "狼人咒缚",
 "狼人形态：",
 "狼爪飞踢",
 "猎人光环",
 "猎头",
 "猎巫时刻",
 "猎怪弹",
 "猫又守卫",
 "现身",
 "玻璃大炮",
 "玻璃大炮",
 "球状闪电",
 "球状闪电减速",
 "生命吸取",
 "生命打击",
 "生命汲取",
 "生死舞台",
 "生气",
 "生物爆破",
 "用火箭弹轰炸一个区域",
 "用鞭子将自己拉向敌人",
 "电击大片区域内的所有敌人",
 "疗伤幽灵",
 "疗愈子弹",
 "疗愈护符",
 "疗愈爆发",
 "疼痛蓄积",
 "疾跑靴",
 "疾速不怠",
 "疾速射击",
 "痛苦",
 "痛苦脉冲",
 "盖斯特夫人",
 "盘丝设困",
 "直击要害",
 "盾男",
 "着陆时：",
 "瞬间消失并重新出现",
 "短暂延迟后眩晕附近的敌人",
 "石像形态",
 "石化",
 "石化飞索",
 "破咒护符",
 "破坏王",
 "破坏球",
 "破阵之势",
 "碎灵子弹",
 "磁力流",
 "祝圣榴弹",
 "祝圣榴弹 - 纯粹",
 "神佑背心",
 "神圣屏障",
 "神秘钢琴",
 "离开区域以逃脱束缚",
 "离开艾娃",
 "秘术余波",
 "秘术射击",
 "秘术愈疗",
 "秘术扩张",
 "秘术爆发",
 "秘术管道",
 "秘术缓速",
 "秘术脆弱",
 "秘法涌动",
 "积雷电容",
 "移动减速",
 "空中霸权",
 "空尖弹",
 "空投",
 "穿幕攻击速度",
 "穿幕行者",
 "穿幕隐身",
 "穿甲弹",
 "穿门时",
 "突刺匕首",
 "窒息熏香",
 "符文手套",
 "箭雨",
 "米娜",
 "粉碎护甲",
 "粉碎跃击",
 "粉碎重拳",
 "粘性炸弹",
 "精华炸弹",
 "精华转移",
 "紧跟同伴",
 "纠缠",
 "纠缠荆棘",
 "红桃",
 "终止咒缚",
 "终结乐章",
 "结束施法",
 "结束灵氲",
 "给敌人注射危险蛇毒",
 "绯红蝠影",
 "绯色狂刃",
 "维克多",
 "缓伤之法",
 "缓速毒瓶",
 "编织一张危险的丝网",
 "编织命运",
 "缠结兽索",
 "缩小射线",
 "缴械前方的敌人",
 "缴械魔咒",
 "羊之坚韧",
 "耀光奇迹",
 "耐力补给",
 "聚焦透镜",
 "能量迸发",
 "脉冲减益",
 "脉冲手雷",
 "脉冲手雷 - 元灵抗性降低",
 "脉冲手雷伤害提升",
 "脱战符文",
 "腥气",
 "腾空飞行并强化武器",
 "艾娃",
 "苦楚灵氲",
 "英雄光环",
 "荡索",
 "莫克双雄",
 "获得减益时：",
 "获得增益时：",
 "获得屏障和移动速度",
 "获得屏障时：",
 "营救光束",
 "落单敌人倒下时：",
 "葛根连结",
 "蓄力射出远击一箭",
 "蓄力射击",
 "蔑视",
 "蔓延火焰",
 "薇妲",
 "虚构屏障",
 "虫障",
 "虹吸弹",
 "蛇影疾行",
 "蜃景",
 "蜘蛛大军",
 "蝰邪",
 "行李车",
 "衰变",
 "被冻结",
 "被减速",
 "被动：",
 "被吸取的生命值",
 "被定身",
 "被放逐",
 "被束缚",
 "被比利锁住",
 "被沉默",
 "被猛击",
 "被眩晕",
 "被禁锢",
 "被缴械",
 "被锁定",
 "被魅惑…",
 "裂光射击",
 "西尔芙",
 "见证精彩",
 "触发时：",
 "让一名敌人入睡",
 "让一名敌方步兵或中立单位灰飞烟灭",
 "诛邪者",
 "诡兔咒术",
 "诡异丝线",
 "赛凌",
 "赤蟥",
 "超凡冷却",
 "超级光束",
 "超速冷却",
 "跃升",
 "跃升之印",
 "跃至高空并射出多重箭矢",
 "跃进爪击",
 "跑酷大师",
 "跟随步兵：",
 "跟随英雄：",
 "跳到友军",
 "跳向敌人",
 "跳弹射击",
 "跳跃射击",
 "身躯虚化",
 "轻盈飞步",
 "达到最大叠加层数时：",
 "迅捷律动",
 "迅捷突击",
 "迅猛突袭",
 "过载冲击",
 "近战",
 "近战攻击时：",
 "近战疗法",
 "近战蓄力",
 "近身决斗",
 "近身猛击",
 "还击",
 "进攻",
 "远击威力",
 "远古战盾",
 "连招",
 "连攻飞刃",
 "连锁闪电",
 "迷人读物",
 "迷你炮塔 - 减速",
 "迷魂一瞥",
 "追猎",
 "逃离酒店",
 "遥控夜枭",
 "部分受到的伤害推迟生效",
 "部署一个治疗之灵",
 "部署会勘察一个区域的雕像",
 "酒店宾客",
 "醉酒",
 "醉酒：",
 "重创一击",
 "重压射击",
 "重新施放",
 "重新施放紧跟同伴",
 "重炮轰击",
 "重炮轰击减速",
 "重生",
 "重装克星",
 "重返阴影",
 "量子闪现",
 "金刚宝衫",
 "金蝉脱壳",
 "金鹅蛋",
 "钉桩",
 "钻地",
 "铁板重甲",
 "铜墙铁壁",
 "铜皮铁骨",
 "锁住",
 "锁定",
 "锁定目标",
 "锁链囚徒",
 "锈蚀枪管",
 "镇尼之印",
 "长尾猛击",
 "门侍",
 "门侍",
 "闪电袭击",
 "闪转腾挪",
 "防守",
 "阴影力量",
 "阴郁炸弹",
 "阿波罗",
 "阿金驳",
 "附魔师纹章",
 "陷阱师",
 "隐忍",
 "隐身",
 "集结冲锋",
 "雨伞戏法",
 "雷姆",
 "雷织漩涡",
 "雷霆风暴",
 "雷霆风暴闪电袭击",
 "雷鸣卷轴",
 "震撼大地",
 "震荡燃烧",
 "霹雳便鞋",
 "青藤",
 "静态电荷",
 "鞭笞",
 "鞭长可及",
 "顽胄韧甲",
 "额外伤害",
 "额外充能",
 "额外武器伤害",
 "额外生命",
 "飞向瞄准的敌人",
 "飞行",
 "飞行斗篷",
 "飞跃斩击",
 "飞跃斩击减速效果",
 "首次穿过门时会获得屏障",
 "驱散魔法",
 "骇然复苏",
 "高速弹",
 "高速装填",
 "魔力装填",
 "魔印增强",
 "魔弹疾袭",
 "魔毯",
 "魔液",
 "麦金妮",
 "黑桃"
];
