' Babel Tower bridge auto-start (self-locating, ASCII-only).
' Generated by scripts\autostart.ps1 - do not write real paths into this file.
' Paths are resolved at runtime from this script's own location, so the
' folder can be extracted/moved/renamed anywhere (incl. non-ASCII paths).
Option Explicit
Dim fso, sh, root, node, server
Set fso = CreateObject("Scripting.FileSystemObject")
Set sh = CreateObject("WScript.Shell")
root = fso.GetParentFolderName(fso.GetParentFolderName(WScript.ScriptFullName))
node = root & "\portable-node\node.exe"
server = root & "\core\bridge_server.js"
If Not fso.FileExists(node) Then node = "node"
If fso.FileExists(server) Then
  sh.Run """" & node & """ """ & server & """", 0, False
End If
